version: '2'
services:
  database:
    scale: 1
    start_on_create: true
  otree:
    scale: 1
    start_on_create: true
  worker:
    scale: 1
    start_on_create: true
  redis:
    scale: 1
    start_on_create: true
